/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ClienteDAO;
import DAO.ICliente;
import DAO.IReserva;
import DAO.ReservaDAO;
import VO.Cliente;
import VO.Reserva;
import java.awt.Color;
import java.awt.FlowLayout;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class ReservaJFrame extends javax.swing.JFrame {
    
    IReserva reservaDao = new ReservaDAO();
    ICliente clienteDao = new ClienteDAO();


    public ReservaJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ImageIcon iconoCancha1 = new ImageIcon(getClass().getResource("/imagenes/cancha.png"));

        //canchaImg.setIcon(iconoCancha1);

        
        ImageIcon iconoBuscar = new ImageIcon(getClass().getResource("/imagenes/search.png"));
        ImageIcon iconoRegistro = new ImageIcon(getClass().getResource("/imagenes/register.png"));
        ImageIcon iconoNuevo = new ImageIcon(getClass().getResource("/imagenes/person.png"));
        ImageIcon iconoLimpiar = new ImageIcon(getClass().getResource("/imagenes/clean.png"));
        ImageIcon iconoAgregar = new ImageIcon(getClass().getResource("/imagenes/add.png"));

        int ancho = 15; // ancho en pixeles que tendra el icono escalado
        int alto = -1; // alto (para que conserve la proporcion pasamos -1)

        // Obtiene un icono en escala con las dimensiones especificadas
        ImageIcon iconoEscala2 = new ImageIcon(iconoBuscar.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        ImageIcon iconoEscRegistro = new ImageIcon(iconoRegistro.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        ImageIcon iconoEscNuevo = new ImageIcon(iconoNuevo.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        ImageIcon iconoEscLimpiar = new ImageIcon(iconoLimpiar.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        ImageIcon iconoEscAgregar = new ImageIcon(iconoAgregar.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        
        ImageIcon iconoEscCancha1 = new ImageIcon(iconoCancha1.getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_DEFAULT));
        ImageIcon iconoEscCancha2 = new ImageIcon(iconoCancha1.getImage().getScaledInstance(80, 80, java.awt.Image.SCALE_DEFAULT));
        
        btnBuscar.setIcon(iconoEscala2);
        btnNuevo.setIcon(iconoEscNuevo);
        btnRegistrar.setIcon(iconoEscRegistro);
        btnLimpiar.setIcon(iconoEscLimpiar);
        btnLimpiar.setIcon(iconoEscLimpiar);
        btnAgregar.setIcon(iconoEscAgregar);
        
        btnCancha1.setIcon(iconoEscCancha2);
        btnCancha2.setIcon(iconoEscCancha2);
        btnCancha3.setIcon(iconoEscCancha2);
        btnCancha4.setIcon(iconoEscCancha2);
        
        
    }
    public void cambiarEstado(){
        String estado = cbtCancha1.getSelectedItem().toString();
        if (estado.equals("Libre")) {
            btnCancha1.setBackground(new Color(89, 206, 143));
        }else if(estado.equals("Mantenimiento")){
            btnCancha1.setBackground(new Color(255, 255, 0));
        }else{
            btnCancha1.setBackground(new Color(255, 30, 0));
        }
    } 
    
    public void insertarFechas(){
        try {
            String cancha = cbCancha.getSelectedItem().toString();
            String dni = txtDNI.getText();
            String fechaInscripcion = LocalDateTime.now().toString();
            String hora = cbHora.getSelectedItem().toString();
            String hora2 = cbHora1.getSelectedItem().toString();
            String fechaInicio = ((JTextField) jcFechaInicio.getDateEditor().getUiComponent()).getText() + " " + hora;
            String fechaFin = ((JTextField) jcFechaFin.getDateEditor().getUiComponent()).getText() + " " + hora2;

            Reserva reserva = new Reserva();

            reserva.setCancha(cancha);
            reserva.setFechaInscripcion(fechaInscripcion);
            reserva.setFechaInicio(fechaInicio);
            reserva.setFechaFin(fechaFin);
            reserva.setCliente(dni);
            
            reservaDao.insertarReserva(reserva);
            JOptionPane.showMessageDialog(null, "Reserva Registrada");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jcFechaInicio = new com.toedter.calendar.JDateChooser();
        cbHora = new javax.swing.JComboBox<>();
        btnLista = new javax.swing.JButton();
        cbCancha = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jcFechaFin = new com.toedter.calendar.JDateChooser();
        cbHora1 = new javax.swing.JComboBox<>();
        btnAlquilerImpl = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarReserva = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnCancha2 = new javax.swing.JButton();
        btnCancha3 = new javax.swing.JButton();
        btnCancha1 = new javax.swing.JButton();
        btnCancha4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbtCancha1 = new javax.swing.JComboBox<>();
        cbtCancha2 = new javax.swing.JComboBox<>();
        cbtCancha3 = new javax.swing.JComboBox<>();
        cbtCancha4 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(232, 249, 253));

        jPanel3.setBackground(new java.awt.Color(232, 249, 253));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 30, 0));
        jLabel2.setText("REGISTRO DE CANCHA");

        btnBuscar.setBackground(new java.awt.Color(89, 206, 143));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("DNI:");

        jLabel4.setText("Nombre:");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(245, 232, 199));

        jLabel5.setText("Apellidos:");

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(245, 232, 199));

        jLabel6.setText("Telefono:");

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(245, 232, 199));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        jLabel7.setText("Email:");

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(245, 232, 199));

        btnRegistrar.setBackground(new java.awt.Color(89, 206, 143));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(89, 206, 143));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(89, 206, 143));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(232, 249, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Inicio:"));

        jcFechaInicio.setDateFormatString("yyyy/MM/dd");

        cbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnLista.setBackground(new java.awt.Color(0, 0, 0));
        btnLista.setForeground(new java.awt.Color(255, 255, 255));
        btnLista.setText("Lista de Reservas");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        cbCancha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancha N°1", "Cancha N°2", "Cancha N°3", "Cancha N°4" }));

        jLabel1.setText("Cancha de Futbol:");

        btnAgregar.setBackground(new java.awt.Color(89, 206, 143));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(232, 249, 253));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Fin:"));

        jcFechaFin.setDateFormatString("yyyy/MM/dd");

        cbHora1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cbHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnAlquilerImpl.setBackground(new java.awt.Color(0, 0, 0));
        btnAlquilerImpl.setForeground(new java.awt.Color(255, 255, 255));
        btnAlquilerImpl.setText("Alquiler Implementos");
        btnAlquilerImpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilerImplActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(7, 7, 7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefono)
                            .addComponent(txtApellido)
                            .addComponent(txtNombre)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cbCancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLista)
                        .addGap(46, 46, 46)
                        .addComponent(btnAlquilerImpl)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLista)
                            .addComponent(btnAlquilerImpl))
                        .addGap(7, 7, 7)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnRegistrar)
                            .addComponent(btnNuevo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addComponent(btnAgregar)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Reserva", jPanel3);

        jPanel4.setBackground(new java.awt.Color(232, 249, 253));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 30, 0));
        jLabel8.setText("Alquiler de Cancha");

        btnBuscarReserva.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscarReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarReserva.setText("Busca Reserva");
        btnBuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReservaActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(236, 204, 178));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado de Canchas:"));

        btnCancha2.setBackground(new java.awt.Color(89, 206, 143));

        btnCancha3.setBackground(new java.awt.Color(89, 206, 143));

        btnCancha1.setBackground(new java.awt.Color(89, 206, 143));

        btnCancha4.setBackground(new java.awt.Color(89, 206, 143));
        btnCancha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancha4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Cancha 2");

        jLabel10.setText("Cancha 3");

        jLabel11.setText("Cancha 1");

        jLabel12.setText("Cancha 4");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancha1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancha3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCancha4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(btnCancha2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancha1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(btnCancha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancha4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancha3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel13.setText("Cancha 1:");

        jLabel14.setText("Cancha 2:");

        jLabel15.setText("Cancha 3:");

        jLabel16.setText("Cancha 4:");

        cbtCancha1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Mantenimiento", "Ocupado" }));
        cbtCancha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbtCancha1MouseClicked(evt);
            }
        });
        cbtCancha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtCancha1ActionPerformed(evt);
            }
        });

        cbtCancha2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Mantenimiento", "Ocupado" }));
        cbtCancha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtCancha2ActionPerformed(evt);
            }
        });

        cbtCancha3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Mantenimiento", "Ocupado" }));
        cbtCancha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtCancha3ActionPerformed(evt);
            }
        });

        cbtCancha4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Mantenimiento", "Ocupado" }));
        cbtCancha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtCancha4ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Lista de Canchas:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbtCancha1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbtCancha2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbtCancha3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbtCancha4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(btnBuscarReserva))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(257, 257, 257))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnBuscarReserva)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cbtCancha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cbtCancha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cbtCancha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbtCancha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
        );

        jTabbedPane1.addTab("Alquiler", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        insertarFechas();
        limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        ListaReserva abrir = new ListaReserva();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnListaActionPerformed

    public void limpiar(){
        txtDNI.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        //Cambiar a modo Editable
        txtNombre.setEditable(true);       
        txtApellido.setEditable(true);
        txtTelefono.setEditable(true);
        txtEmail.setEditable(true);
        
        //Cambiar color de fondo
        txtNombre.setBackground(Color.WHITE);
        txtApellido.setBackground(Color.WHITE);
        txtTelefono.setBackground(Color.WHITE);
        txtEmail.setBackground(Color.WHITE);
        
        limpiar();
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String dni = txtDNI.getText();
        
        Cliente cliente = clienteDao.buscarDNI(dni);
        
        if(txtDNI.getText().equals("")){
            JOptionPane.showMessageDialog(null, "El campo esta vacio");
        }else{
            if(cliente != null){         
                txtNombre.setText(cliente.getNombre());
                txtApellido.setText(cliente.getApellido());
                txtTelefono.setText(cliente.getTelefono());
                txtEmail.setText(cliente.getEmail());
            }else{
                JOptionPane.showMessageDialog(null,"¡Error, DNI no registrado!","Mensaje",JOptionPane.ERROR_MESSAGE);
                limpiar();
            }        
        }   
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAlquilerImplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilerImplActionPerformed
        // TODO add your handling code here:
        ImplementosJFrame abrir = new ImplementosJFrame();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAlquilerImplActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try{
            String dni = txtDNI.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String telefono = txtTelefono.getText();
            String email = txtEmail.getText();
            
            Cliente cliente = new Cliente();
            cliente.setDni(dni);
            cliente.setNombre(nombre);
            cliente.setApellido(apellido);
            cliente.setTelefono(telefono);
            cliente.setEmail(email);
            
            clienteDao.agregar(cliente);
            JOptionPane.showMessageDialog(null, "Cliente registrada");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservaActionPerformed
        // TODO add your handling code here:
        ListaReserva abrir = new ListaReserva();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarReservaActionPerformed

    private void btnCancha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancha4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancha4ActionPerformed

    private void cbtCancha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtCancha1MouseClicked
        // TODO add your handling code here:
        /*String estado = cbtCancha1.getSelectedItem().toString();
        if (estado.equals("Libre")) {
            btnCancha1.setBackground(new Color(89, 206, 143));
        }else if(estado.equals("Mantenimiento")){
            btnCancha1.setBackground(new Color(255, 255, 0));
        }else{
            btnCancha1.setBackground(new Color(255, 30, 0));
        }*/
    }//GEN-LAST:event_cbtCancha1MouseClicked

    private void cbtCancha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtCancha1ActionPerformed
        // TODO add your handling code here:
        String estado = cbtCancha1.getSelectedItem().toString();
        if (estado.equals("Libre")) {
            btnCancha1.setBackground(new Color(89, 206, 143));
        }else if(estado.equals("Mantenimiento")){
            btnCancha1.setBackground(new Color(255, 255, 0));
        }else{
            btnCancha1.setBackground(new Color(255, 30, 0));
        }
    }//GEN-LAST:event_cbtCancha1ActionPerformed

    private void cbtCancha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtCancha2ActionPerformed
        // TODO add your handling code here:
        String estado = cbtCancha2.getSelectedItem().toString();
        if (estado.equals("Libre")) {
            btnCancha2.setBackground(new Color(89, 206, 143));
        }else if(estado.equals("Mantenimiento")){
            btnCancha2.setBackground(new Color(255, 255, 0));
        }else{
            btnCancha2.setBackground(new Color(255, 30, 0));
        }
    }//GEN-LAST:event_cbtCancha2ActionPerformed

    private void cbtCancha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtCancha3ActionPerformed
        // TODO add your handling code here:
        String estado = cbtCancha3.getSelectedItem().toString();
        if (estado.equals("Libre")) {
            btnCancha3.setBackground(new Color(89, 206, 143));
        }else if(estado.equals("Mantenimiento")){
            btnCancha3.setBackground(new Color(255, 255, 0));
        }else{
            btnCancha3.setBackground(new Color(255, 30, 0));
        }
    }//GEN-LAST:event_cbtCancha3ActionPerformed

    private void cbtCancha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtCancha4ActionPerformed
        // TODO add your handling code here:
        String estado = cbtCancha4.getSelectedItem().toString();
        if (estado.equals("Libre")) {
            btnCancha4.setBackground(new Color(89, 206, 143));
        }else if(estado.equals("Mantenimiento")){
            btnCancha4.setBackground(new Color(255, 255, 0));
        }else{
            btnCancha4.setBackground(new Color(255, 30, 0));
        }
    }//GEN-LAST:event_cbtCancha4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAlquilerImpl;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarReserva;
    private javax.swing.JButton btnCancha1;
    private javax.swing.JButton btnCancha2;
    private javax.swing.JButton btnCancha3;
    private javax.swing.JButton btnCancha4;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbCancha;
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JComboBox<String> cbHora1;
    private javax.swing.JComboBox<String> cbtCancha1;
    private javax.swing.JComboBox<String> cbtCancha2;
    private javax.swing.JComboBox<String> cbtCancha3;
    private javax.swing.JComboBox<String> cbtCancha4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jcFechaFin;
    private com.toedter.calendar.JDateChooser jcFechaInicio;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
